#!/bin/bash

# Usage ./setup_year <year>
# Example:
# ./setup_year
# ./setup_year 2024

if [ -z "$1" ]; then
    year=$(date +%Y)
else
    year=$1
fi

mkdir -p $year
cd $year
mkdir -p inputs/
touch inputs/.gitkeep
mkdir -p inputs/sample/
mkdir -p timelapse/
touch $year.gif

# Generate README.md file
cat <<EOF > README.md
# advent-of-code

## [Advent of Code $year](https://adventofcode.com/$year)

<img src="https://raw.githubusercontent.com/vchrombie/advent-of-code/refs/heads/master/$year/$year.gif" width="650" align="right">

- [ ] Day 1
- [ ] Day 2
- [ ] Day 3
- [ ] Day 4
- [ ] Day 5
- [ ] Day 6
- [ ] Day 7
- [ ] Day 8
- [ ] Day 9
- [ ] Day 10
- [ ] Day 11
- [ ] Day 12
- [ ] Day 13
- [ ] Day 14
- [ ] Day 15
- [ ] Day 16
- [ ] Day 17
- [ ] Day 18
- [ ] Day 19
- [ ] Day 20
- [ ] Day 21
- [ ] Day 22
- [ ] Day 23
- [ ] Day 24
- [ ] Day 25
EOF

cd ..
rm README.md
ln -s $year/README.md README.md 

echo "ready for $year"
