#!/bin/bash

# Usage ./setup_day <day>
# Example:
# ./setup_day
# ./setup_day 08

if [ -z "$1" ]; then
    day=$(date +%d)
else
    day=$1
fi

cd $(date +%Y)/
touch inputs/$day.txt
touch inputs/sample/$day.txt
cp ../day.py .
sed -i '' "s|INPUT_FILE = 'input.txt'|INPUT_FILE = 'inputs/$day.txt'|" day.py
sed -i '' "s|SAMPLE_FILE = 'sample.txt'|SAMPLE_FILE = 'inputs/sample/$day.txt'|" day.py
sed -i '' '1,2d' day.py
mv day.py $day.py

code $day.py inputs/$day.txt inputs/sample/$day.txt

echo "ready for day $day"
