#!/usr/bin/env python3

"""
Script to take a screenshot of the calendar and save it as a png file. It also
genenate a gif file as a timelapse of the year.

Requirements:
    - mss: `pip install mss`
    - ImageMagick: `brew install imagemagick`

Usage:
$ python3 timelapse
$ ./timelapse
"""

import os
import shutil
import mss.tools

from time import sleep
from datetime import datetime

with mss.mss() as sct:
    sleep(1)

    dt = datetime.today()
    day, year = dt.strftime('%d'), dt.strftime('%Y')
    day_png = f"{day}.png"

    monitor = {"top": 223, "left": 0, "width": 570, "height": 610}
    sct_img = sct.grab(monitor)
    mss.tools.to_png(sct_img.rgb, sct_img.size, output=day_png)

    shutil.move(day_png, os.path.join(f'{year}', 'timelapse', day_png))

    os.system(f"convert -delay 50 {year}/timelapse/*.png {year}/{year}.gif")
